import {STORAGE_KEY,emptyProgress,validateProgress,scheduleCard} from './progress.mjs';
const main=document.querySelector('#main'),content=document.querySelector('#content'),summary=document.querySelector('#summary');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inlineMath=s=>esc(s).replace(/\\textbf\{([^{}]*)\}/g,'<strong>$1</strong>').replace(/\\emph\{([^{}]*)\}/g,'<em>$1</em>');
const texLabel=(x,y,tex,size=15)=>`<g data-tex="${esc(tex)}" data-x="${x}" data-y="${y}" data-size="${size}"></g>`;
const cap=s=>s.charAt(0).toUpperCase()+s.slice(1);
const link=(route,label,cls='')=>`<a class="${cls}" href="#/${esc(route)}">${inlineMath(label)}</a>`;
const pdfLink=path=>`exams/${path.split('/').map(encodeURIComponent).join('/')}`;
const math=s=>`<div class="math-text">${String(s??'').split(/\n\s*\n/).map(t=>'<p>'+inlineMath(t)+'</p>').join('')}</div>`;
const $=s=>main.querySelector(s);
const $$=s=>[...main.querySelectorAll(s)];
let data,progress,ids,routeVersion=0,cardSession=[],cardIndex=0,cardRevealed=false,cardFilterKey='';
function announce(s){const a=document.querySelector('#announcement');a.textContent=s;clearTimeout(a.timeout);a.timeout=setTimeout(()=>a.textContent='',5000);}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));}catch{announce('Browser storage is unavailable or full. Export your progress to keep it.');}updateSummary();}
function state(p){return progress.problems[p.id]||{status:'new',bookmark:false,notes:'',hints:0};}
function setProblem(id,changes){progress.problems[id]={...state({id}),...changes};save();}
function updateSummary(){if(!data)return;const ps=Object.values(progress.problems);summary.innerHTML=`<p>${ps.filter(p=>p.status==='mastered').length} / 757 mastered<br>${ps.filter(p=>p.status==='review').length} to revisit<br>${data.cards.filter(c=>(progress.cards[c.id]?.due||0)<=Date.now()).length} cards due</p>`;}
async function typeset(){if(window.MathJax?.startup?.promise){await MathJax.startup.promise;await MathJax.typesetPromise([main]);await typesetFigureLabels();}}
async function typesetFigureLabels(){
 for(const label of main.querySelectorAll('[data-tex]:not([data-rendered])')){
  const rendered=await MathJax.tex2svgPromise(label.dataset.tex,{display:false});
  if(!label.isConnected)continue;
  const svg=rendered.querySelector('svg'),box=svg.getAttribute('viewBox').split(/\s+/).map(Number),height=Number(label.dataset.size);
  svg.setAttribute('width',height*box[2]/box[3]);svg.setAttribute('height',height);
  svg.setAttribute('x',label.dataset.x);svg.setAttribute('y',Number(label.dataset.y)-height);
  svg.setAttribute('aria-label',label.dataset.tex);label.append(svg);label.dataset.rendered='true';
 }
}
function currentRoute(){const [path,q='']=(location.hash.slice(2)||'curriculum').split('?');return {parts:path.split('/'),query:new URLSearchParams(q)};}
function filters(query,extra='',topics=true){
  const options=(values,key)=>values.map(([v,l])=>`<option value="${esc(v)}" ${query.get(key)===v?'selected':''}>${esc(l)}</option>`).join('');
  return `<form id="filters" class="filters"><label>Subject<select name="subject">${options([['','Both subjects'],['analysis','Analysis'],['linear algebra','Linear algebra']],'subject')}</select></label>${topics?`<label>Topic<select name="module">${options([['','All topics'],...data.modules.map(m=>[m.id,m.title])],'module')}</select></label>`:''}${extra}<label>Search<input name="search" type="search" value="${esc(query.get('search')||'')}" placeholder="Title, tool or problem text"></label><button>Apply filters</button></form>`;
}
function bindFilters(base){$('#filters')?.addEventListener('submit',e=>{e.preventDefault();const q=new URLSearchParams();new FormData(e.target).forEach((v,k)=>{if(v)q.set(k,v)});location.hash=`/${base}?${q}`;});}
function matches(p,q){return (!q.get('subject')||p.subject===q.get('subject'))&&(!q.get('module')||p.modules.includes(q.get('module')))&&(!q.get('year')||String(p.year)===q.get('year'))&&(!q.get('status')||(q.get('status')==='bookmarked'?state(p).bookmark:state(p).status===q.get('status')))&&(!q.get('search')||[p.id,p.title,p.prompt,...p.theorems].join(' ').toLowerCase().includes(q.get('search').toLowerCase()));}
function problemRow(p){const s=state(p);return `<article class="problem-row"><div class="meta">${cap(p.subject)} · ${cap(p.sitting)} ${p.year} · ${esc(p.printedLabel||`Problem ${p.number}`)} · ${esc(s.status)}${s.bookmark?' · bookmarked':''}</div><h3>${link('problem/'+p.id,p.title)}</h3>${p.modules.map(id=>`<span class="tag">${esc(data.moduleMap[id].title)}</span>`).join('')}</article>`;}
function curriculum(q){
  const ms=data.modules.filter(m=>!q.get('subject')||m.subject===q.get('subject'));
  content.innerHTML=`<h1>Guided curriculum</h1><div class="actions">${link('curriculum?subject=analysis','Analysis','button')}${link('curriculum?subject=linear%20algebra','Linear algebra','button')}${link('curriculum','Both subjects','button')}</div><div class="cards-grid">${ms.map(m=>{const ls=data.lessons.filter(l=>l.module===m.id),ps=data.problems.filter(p=>p.modules.includes(m.id));return `<section class="topic"><div class="index">${cap(m.subject)}, ${ls.filter(l=>progress.lessons[l.id]).length}/${ls.length} lessons read</div><h2>${link('topic/'+m.id,m.title)}</h2><div class="small">${ls.length} lessons - ${ps.length} practice problems</div></section>`}).join('')}</div>`;
}
function topic(id){
 const m=data.moduleMap[id];if(!m)return missing();
 const ls=data.lessons.filter(l=>l.module===id),ps=data.problems.filter(p=>p.modules.includes(id));
 content.innerHTML=`<h1>${esc(m.title)}</h1><ol>${ls.map(l=>`<li>${link('lesson/'+l.id,l.title)}${progress.lessons[l.id]?' — read':''}</li>`).join('')}</ol><p>${link('cards?module='+id,'Study this topic’s flashcards','button')}</p>${ps.slice().sort((a,b)=>b.year-a.year).slice(0,8).map(problemRow).join('')}<p>${link('problems?module='+id,`All ${ps.length} problems in this topic`,'button')}</p>`;
}
function problems(q){
 const ps=data.problems.filter(p=>matches(p,q)).sort((a,b)=>b.year-a.year||a.id.localeCompare(b.id));
 const totalPages=Math.max(1,Math.ceil(ps.length/25)),page=Math.max(1,Math.min(totalPages,Number(q.get('page'))||1));
 const years=[...new Set(data.problems.map(p=>p.year))].sort((a,b)=>b-a);
 const extra=`<label>Year<select name="year"><option value="">All years</option>${years.map(y=>`<option ${q.get('year')===String(y)?'selected':''}>${y}</option>`).join('')}</select></label><label>My status<select name="status">${[['','All problems'],['new','New'],['attempted','Attempted'],['review','To revisit'],['mastered','Mastered'],['bookmarked','Bookmarked']].map(([v,l])=>`<option value="${v}" ${q.get('status')===v?'selected':''}>${l}</option>`).join('')}</select></label>`;
 const pageLink=(n,l)=>{const params=new URLSearchParams(q);params.set('page',n);return link('problems?'+params,l,'button')};
 content.innerHTML=`<h1>Problem practice</h1>${filters(q,extra)}<p role="status" class="result-count">${ps.length} of 757 problems · page ${page} of ${totalPages}</p>${ps.length?ps.slice((page-1)*25,page*25).map(problemRow).join(''):'<p class="empty">No problems match these filters.</p>'}<div class="pagination">${page>1?pageLink(page-1,'Previous page'):''}${page<totalPages?pageLink(page+1,'Next page'):''}</div>`;bindFilters('problems');
}
function sourceLinks(p){const pages=p.sourcePages||[p.sourcePage];return `<a href="${pdfLink(p.sourcePath)}#page=${p.sourcePage}" target="_blank" rel="noopener">Original PDF · page${pages.length>1?'s':''} ${pages.join(', ')}</a>`;}
function problem(id){
 const p=data.problemMap[id];if(!p)return missing();const s=state(p);
 content.innerHTML=`<p class="breadcrumb">${link('problems','Problems')} / ${link('exam/'+p.examId,cap(p.sitting)+' '+p.year+' '+cap(p.subject))}</p><h1>${inlineMath(p.title)}</h1><p class="meta">${esc(p.id)} · ${esc(p.printedLabel||`Problem ${p.number}`)} · ${sourceLinks(p)}</p>${p.note?`<div class="note">${math(p.note)}</div>`:''}<section class="exercise" aria-label="Problem statement">${math(p.prompt)}</section><div class="actions"><button id="bookmark">${s.bookmark?'Remove bookmark':'Bookmark problem'}</button><label>My status <select id="status">${[['new','New'],['attempted','Attempted'],['review','To revisit'],['mastered','Mastered']].map(([v,l])=>`<option value="${v}" ${v===s.status?'selected':''}>${l}</option>`).join('')}</select></label></div><h2>Step-by-step hints</h2><div id="hints">${p.hints.slice(0,s.hints).map((h,i)=>`<div class="hint"><strong>Hint ${i+1}</strong>${math(h)}</div>`).join('')}</div><button id="hint" ${s.hints>=p.hints.length?'disabled':''}>Reveal next hint</button><h2>Worked solution</h2><button id="solution-toggle" aria-expanded="false">Reveal worked solution</button><section id="solution" hidden class="answer">${math(p.solution)}${p.meridianPaths?meridian(p.meridianPaths):''}</section><h2>Tools and related lessons</h2><p>${p.theorems.map(t=>`<span class="tag">${inlineMath(t)}</span>`).join('')}</p><ul>${p.lessons.map(l=>`<li>${link('lesson/'+l,data.lessonMap[l].title)}</li>`).join('')}</ul><p>${p.modules.map(m=>link('topic/'+m,data.moduleMap[m].title)).join(' · ')}</p>`;
 $('#bookmark').onclick=e=>{setProblem(id,{bookmark:!state(p).bookmark});e.target.textContent=state(p).bookmark?'Remove bookmark':'Bookmark problem';};
 $('#status').onchange=e=>setProblem(id,{status:e.target.value});
 $('#hint').onclick=async e=>{const n=Math.min(p.hints.length,state(p).hints+1);setProblem(id,{hints:n,status:state(p).status==='new'?'attempted':state(p).status});$('#status').value=state(p).status;$('#hints').innerHTML=p.hints.slice(0,n).map((h,i)=>`<div class="hint"><strong>Hint ${i+1}</strong>${math(h)}</div>`).join('');e.target.disabled=n===p.hints.length;await typeset();};
 $('#solution-toggle').onclick=async e=>{const open=$('#solution').hidden;$('#solution').hidden=!open;e.target.setAttribute('aria-expanded',String(open));e.target.textContent=open?'Hide worked solution':'Reveal worked solution';await typeset();};
}
function meridian(paths){return `<figure><svg class="visual" viewBox="0 0 110 102" role="img" aria-label="Meridian of spindle surface, with inner bounded region B, annular bounded region A and exterior C"><path d="M10 95V3 M10 50H97" stroke="#778471" fill="none"/>${paths.map(d=>`<path d="${d}" stroke="#28613b" stroke-width=".7" fill="none"/>`).join('')}${[[43,45,'A'],[18,45,'B'],[76,45,'C'],[2,6,'z'],[96,49,'\\rho'],[14,15,'\\sqrt{3}'],[14,91,'-\\sqrt{3}']].map(([x,y,t])=>texLabel(x,y,t,6)).join('')}<circle cx="10" cy="18.82" r="1"/><circle cx="10" cy="81.18" r="1"/></svg><figcaption class="small">Revolve about the vertical axis. The two sheets meet at the marked axis points.</figcaption></figure>`;}
function exams(q){
 const es=data.exams.filter(e=>(!q.get('subject')||e.subject===q.get('subject'))&&(!q.get('year')||String(e.year)===q.get('year'))&&(!q.get('search')||`${e.subject} ${e.year} ${e.sitting}`.includes(q.get('search').toLowerCase()))).sort((a,b)=>b.year-a.year||a.id.localeCompare(b.id));
 content.innerHTML=`<h1>Exam archive</h1>${filters(q,`<label>Year<select name="year"><option value="">All years</option>${Array.from({length:27},(_,i)=>2026-i).map(y=>`<option ${q.get('year')===String(y)?'selected':''}>${y}</option>`).join('')}</select></label>`,false)}<p role="status">${es.length} exams</p>${es.map(e=>`<article class="problem-row"><h3>${link('exam/'+e.id,`${cap(e.subject)} · ${cap(e.sitting)} ${e.year}`)}</h3><p class="small">${e.problemIds.length} problems · ${e.problemIds.filter(id=>state({id}).status==='mastered').length} mastered</p><div>${e.sources.map(s=>`<a href="${pdfLink(s)}" target="_blank">${esc(s)}</a>`).join(' · ')}</div></article>`).join('')}`;bindFilters('exams');
}
function exam(id){const e=data.examMap[id];if(!e)return missing();content.innerHTML=`<p class="breadcrumb">${link('exams','Exam archive')}</p><h1>${cap(e.subject)} · ${cap(e.sitting)} ${e.year}</h1><p>${e.sources.map(s=>`<a href="${pdfLink(s)}" target="_blank">Open original exam PDF</a>`).join(' · ')}</p>${id==='A-2013-august'?'<p><a href="exams/analysis/august-2013.pdf" target="_blank">Analysis-only page copy</a></p>':''}<p>Use the original PDF for its printed instructions, scoring rules and source wording. The study statements below summarize every main question and include every subpart in the worked solutions.</p>${e.problemIds.map(id=>{const p=data.problemMap[id];return problemRow(p)+`<details class="disclosure"><summary>Read problem statement</summary>${math(p.prompt)}</details>`}).join('')}`;}
function theorems(q){const ls=data.lessons.filter(l=>(!q.get('subject')||data.moduleMap[l.module].subject===q.get('subject'))&&(!q.get('module')||l.module===q.get('module'))&&(!q.get('search')||`${l.title} ${l.statement}`.toLowerCase().includes(q.get('search').toLowerCase())));content.innerHTML=`<h1>Theorems and definitions</h1>${filters(q)}<p role="status">${ls.length} lessons</p>${ls.map(l=>`<article class="problem-row"><div class="meta">${esc(data.moduleMap[l.module].title)}${progress.lessons[l.id]?' · read':''}</div><h3>${link('lesson/'+l.id,l.title)}</h3></article>`).join('')}`;bindFilters('theorems');}
function lesson(id){const l=data.lessonMap[id];if(!l)return missing();const ps=data.problems.filter(p=>p.lessons.includes(id)).sort((a,b)=>b.year-a.year);content.innerHTML=`<p class="breadcrumb">${link('theorems','Theorems')} / ${link('topic/'+l.module,data.moduleMap[l.module].title)}</p><h1>${inlineMath(l.title)}</h1><h2>Statement</h2>${math(l.statement)}<h2>Proof</h2>${math(l.proof)}${l.visual?'<h2>Explore the calculation</h2><div id="visual-area"></div>':''}${l.definitions.length?`<h2>Definitions to recall</h2>${l.definitions.map(d=>`<details class="disclosure"><summary>${inlineMath(d.question)}</summary>${math(d.answer)}</details>`).join('')}`:''}<div class="actions"><label><input id="lesson-read" type="checkbox" ${progress.lessons[id]?'checked':''}> Mark this lesson read</label>${link('cards?lesson='+id,'Practice recall','button')}</div><h2>Apply it in an exam problem</h2>${ps.length?ps.slice(0,6).map(problemRow).join(''):`<p>${link('problems?module='+l.module,'Browse problems in this topic')}</p>`}`;$('#lesson-read').onchange=e=>{if(e.target.checked)progress.lessons[id]=true;else delete progress.lessons[id];save();};if(l.visual)visual(l.visual);}
function makeCards(){return data.lessons.flatMap(l=>[{id:l.id+'-statement',lesson:l.id,module:l.module,question:`State ${l.title}, including all hypotheses.`,answer:l.statement},{id:l.id+'-proof',lesson:l.id,module:l.module,question:`How do you prove ${l.title}?`,answer:l.proof},...l.definitions.map((d,i)=>({id:l.id+'-definition-'+i,lesson:l.id,module:l.module,...d}))]);}
function cards(q){
 const key=q.toString();const due=q.get('mode')!=='all';
 const eligible=data.cards.filter(c=>(!q.get('subject')||data.moduleMap[c.module].subject===q.get('subject'))&&(!q.get('module')||c.module===q.get('module'))&&(!q.get('lesson')||c.lesson===q.get('lesson'))&&(!due||(progress.cards[c.id]?.due||0)<=Date.now()));
 if(key!==cardFilterKey||cardIndex>=cardSession.length){cardSession=eligible.slice().sort((a,b)=>(progress.cards[a.id]?.due||0)-(progress.cards[b.id]?.due||0));cardIndex=0;cardFilterKey=key;cardRevealed=false;}
 const c=cardSession[cardIndex];
 content.innerHTML=`<h1>Theorem and definition flashcards</h1><form id="filters" class="filters"><label>Topic<select name="module"><option value="">All topics</option>${data.modules.map(m=>`<option value="${m.id}" ${q.get('module')===m.id?'selected':''}>${esc(m.title)}</option>`).join('')}</select></label><label>Cards<select name="mode"><option value="due">Due and new</option><option value="all" ${!due?'selected':''}>All cards</option></select></label>${q.get('lesson')?`<input type="hidden" name="lesson" value="${esc(q.get('lesson'))}">`:''}<button>Choose cards</button></form><p class="meta">${eligible.length} eligible · ${data.cards.length} cards in the complete library</p>${c?`<div class="meta">Card ${cardIndex+1} of ${cardSession.length} · ${link('lesson/'+c.lesson,data.lessonMap[c.lesson].title)}</div><section class="flashcard"><h2>${inlineMath(c.question)}</h2><div id="card-answer" ${cardRevealed?'':'hidden'} class="answer">${math(c.answer)}</div></section><div class="actions"><button id="card-reveal" ${cardRevealed?'hidden':''}>Reveal answer</button><div id="card-ratings" ${cardRevealed?'':'hidden'}><button data-rating="again">Again · 1 minute</button> <button data-rating="hard">Hard · ${Math.round(Math.max(1,(progress.cards[c.id]?.interval||0)*1.2))} days</button> <button data-rating="good">Good · ${Math.round(Math.max(3,(progress.cards[c.id]?.interval||0)*2))} days</button> <button data-rating="easy">Easy · ${Math.round(Math.max(7,(progress.cards[c.id]?.interval||0)*2.5))} days</button></div><button id="card-skip">Skip</button></div>`:'<p class="empty">No cards are due in this selection. Choose “All cards” to practice ahead of schedule.</p>'}`;bindFilters('cards');
 if(c){$('#card-reveal').onclick=async()=>{cardRevealed=true;$('#card-answer').hidden=false;$('#card-ratings').hidden=false;$('#card-reveal').hidden=true;await typeset();};$$('[data-rating]').forEach(b=>b.onclick=async()=>{progress.cards[c.id]=scheduleCard(progress.cards[c.id],b.dataset.rating);save();cardIndex++;cardRevealed=false;if(cardIndex>=cardSession.length){cardSession=[];cardIndex=0;cardFilterKey='';}cards(q);await typeset();});$('#card-skip').onclick=async()=>{cardIndex++;cardRevealed=false;cards(q);await typeset();};}
}
function downloadJSON(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function progressPage(){
 const counts=s=>data.problems.filter(p=>state(p).status===s).length;
 content.innerHTML=`<h1>My progress</h1><div class="audit"><div><strong>${counts('mastered')}</strong>mastered</div><div><strong>${counts('attempted')}</strong>attempted</div><div><strong>${counts('review')}</strong>to revisit</div><div><strong>${Object.keys(progress.lessons).length}</strong>lessons read</div></div>${data.modules.map(m=>{const ps=data.problems.filter(p=>p.modules.includes(m.id)),n=ps.filter(p=>state(p).status==='mastered').length;return `<div class="progress-line"><span>${link('topic/'+m.id,m.title)}</span><span>${n} / ${ps.length}</span></div><progress aria-label="${esc(m.title)} mastered" value="${n}" max="${Math.max(1,ps.length)}"></progress>`}).join('')}<h2>Keep or restore a backup</h2><div class="actions"><button id="export">Export progress</button><label>Import progress JSON <input id="import" type="file" accept="application/json,.json"></label></div><p class="small">Import replaces this app’s existing progress after validating the file. Other site data is untouched.</p><div id="import-review" hidden class="callout"></div><h2>Clear my study data</h2><p>This clears all notes, bookmarks, ratings and lesson checks for this app in this browser.</p><button class="danger" id="reset">Clear progress…</button><div id="reset-confirm" hidden class="callout"><p>Clear all study progress? Export a backup first if you want to keep it.</p><button class="danger" id="reset-yes">Yes, clear my progress</button> <button id="reset-no">Cancel</button></div><h2>Study archive</h2><p>757 solved problems, 118 subject sittings, 119 preserved original PDFs, ${data.lessons.length} lesson pages and ${data.cards.length} flashcards. The master PDF contains 549 pages. Every archived problem received a second mathematical self-check; these are independent study solutions rather than an official answer key.</p>`;
 $('#export').onclick=()=>{downloadJSON(progress,'pitt-prelim-progress-'+new Date().toISOString().slice(0,10)+'.json');let box=$('#export-copy');if(!box){box=document.createElement('details');box.id='export-copy';$('#import-review').before(box);}box.open=true;box.innerHTML=`<summary>Backup JSON (copy if your browser blocks downloads)</summary><label for="backup-json">Complete backup</label><textarea id="backup-json" readonly>${esc(JSON.stringify(progress,null,2))}</textarea>`;};
 $('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>10000000)throw Error('Progress files must be below 10 MB.');const incoming=validateProgress(JSON.parse(await f.text()),ids);const box=$('#import-review');box.hidden=false;box.innerHTML=`<p>Valid backup: ${Object.keys(incoming.problems).length} problem records, ${Object.keys(incoming.cards).length} card records, ${Object.keys(incoming.lessons).length} lessons. Replace the current progress?</p><button id="import-yes">Import this backup</button> <button id="import-no">Cancel</button>`;$('#import-yes').onclick=()=>{progress=incoming;save();cardFilterKey='';cardSession=[];progressPage();announce('Backup imported.');};$('#import-no').onclick=()=>{box.hidden=true;e.target.value='';};}catch(err){announce('Import failed: '+err.message);e.target.value='';}};
 $('#reset').onclick=()=>$('#reset-confirm').hidden=false;$('#reset-no').onclick=()=>$('#reset-confirm').hidden=true;$('#reset-yes').onclick=()=>{progress=emptyProgress();save();cardSession=[];cardFilterKey='';progressPage();announce('Study progress cleared.');};
}
function missing(){content.innerHTML='<h1>Page not found</h1><p>'+link('curriculum','Return to the curriculum')+'</p>';}
async function render(){
 const version=++routeVersion;if(window.MathJax?.typesetClear)MathJax.typesetClear([main]);
 const {parts:[page,id],query}=currentRoute();
 const renders={curriculum:()=>curriculum(query),topic:()=>topic(id),problems:()=>problems(query),problem:()=>problem(id),exams:()=>exams(query),exam:()=>exam(id),theorems:()=>theorems(query),lesson:()=>lesson(id),cards:()=>cards(query),progress:progressPage};
 (renders[page]||missing)();document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')===`#/${page}`||({topic:'curriculum',problem:'problems',exam:'exams',lesson:'theorems'}[page]&&a.getAttribute('href')===`#/${{topic:'curriculum',problem:'problems',exam:'exams',lesson:'theorems'}[page]}`))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 document.title=(main.querySelector('h1')?.textContent||'Pitt prelim study')+' | Pitt Prelim Study';
 await typeset();if(version===routeVersion){window.scrollTo(0,0);main.focus({preventScroll:true});}
}
// Each figure displays an exact elementary example; it does not stand in for a proof.
function visual(kind){
 const area=$('#visual-area');let controls,draw;
 const range=(id,label,min,max,value,step=1)=>`<label>${label}<input id="${id}" type="range" min="${min}" max="${max}" value="${value}" step="${step}"></label>`;
 const svg=body=>`<svg class="visual" viewBox="0 0 620 320" role="img" aria-label="${kind} illustration">${body}</svg>`;
 const figure=(body,caption)=>svg(body)+`<div class="small" aria-live="polite">${math(caption)}</div>`;
 const line=(x1,y1,x2,y2,color='#28613b',dash='')=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="2" ${dash?'stroke-dasharray="5 4"':''}/>`;
 const text=texLabel;
 if(kind==='contraction'){
  controls=range('q',String.raw`Contraction factor \(q\)`,0,.95,.5,.05)+range('iterations','Iterations',0,18,4);
  draw=()=>{const q=+$('#q').value,n=+$('#iterations').value,x=q**n;return figure(line(45,180,575,180,'#778471')+text(45,220,'0')+text(520,220,'x_0=1')+Array.from({length:n+1},(_,k)=>`<circle cx="${45+530*q**k}" cy="180" r="${k===n?7:3}" fill="${k===n?'#183526':'#91ac76'}"/>`).join(''),String.raw`\(T(x)=${q.toFixed(2)}x,\quad x_n=q^n,\quad n=${n}.\) The fixed point is \(0\). Actual error and geometric-tail bound: \(|x_n|=q^n=${x.toFixed(6)}\).`);};
 }else if(kind==='projection'){
  controls=range('angle','Line angle (degrees)',0,180,30)+range('vx',String.raw`Vector coordinate \(x\)`,-3,3,2,.1)+range('vy',String.raw`Vector coordinate \(y\)`,-2,2,1.5,.1);
  draw=()=>{const a=+$('#angle').value*Math.PI/180,x=+$('#vx').value,y=+$('#vy').value,u=Math.cos(a),v=Math.sin(a),dot=x*u+y*v,px=dot*u,py=dot*v;const X=t=>310+65*t,Y=t=>180-65*t;return figure(line(35,180,585,180,'#ced7c3')+line(310,25,310,300,'#ced7c3')+line(X(-4*u),Y(-4*v),X(4*u),Y(4*v),'#91ac76')+line(310,180,X(x),Y(y))+line(310,180,X(px),Y(py),'#8e6e31')+line(X(x),Y(y),X(px),Y(py),'#657963',true)+text(X(x)+7,Y(y),'v')+text(X(px)+7,Y(py)+18,'Pv'),String.raw`\(Pv=(${px.toFixed(2)},${py.toFixed(2)})\). The unit direction is \(u=(\cos\theta,\sin\theta)\), and \((v-Pv)\cdot u=0\).`);};
 }else if(kind==='gershgorin'){
  controls=range('off',String.raw`Off-diagonal value \(a\)`,0,1,.15,.05);
  draw=()=>{const a=+$('#off').value,r=2*a,centers=[1,3,5],scale=65;return figure(line(45,170,575,170,'#a0b08e')+centers.map(c=>`<circle cx="${100+(c-1)*scale}" cy="170" r="${r*scale}" fill="#e4efd2" fill-opacity=".6" stroke="#28613b"/>`+text(94+(c-1)*scale,176,String(c))).join(''),String.raw`\[A=\begin{pmatrix}1&a&a\\a&3&a\\a&a&5\end{pmatrix},\qquad a=${a.toFixed(2)}.\] Each disc has radius \(2a=${r.toFixed(2)}\). `+(a<.5?'The discs are disjoint, so each contains exactly one eigenvalue.':'The discs touch or overlap, so individual counts no longer follow.'));};
 }else if(kind==='jordan'){
  controls='<label>Nilpotent block sizes<select id="blocks"><option>3,2,1</option><option>4,2</option><option>2,2,2</option><option>6</option></select></label>';
  draw=()=>{const blocks=$('#blocks').value.split(',').map(Number),dims=Array.from({length:7},(_,k)=>blocks.reduce((s,n)=>s+Math.min(k,n),0));return figure(dims.map((d,k)=>`<rect x="${50+k*78}" y="${260-d*30}" width="35" height="${d*30}" fill="#759850"/>`+text(52+k*78,283,String(k))+text(54+k*78,250-d*30,String(d))).join(''),String.raw`\(\dim\ker N^k=\sum_j\min(k,b_j),\quad k=0,1,\ldots,6\), for block sizes \((b_j)=(${blocks.join(',')})\). Differences \(\dim\ker N^k-\dim\ker N^{k-1}\) count blocks of length at least \(k\).`);};
 }else if(kind==='uniform'){
  controls=range('n',String.raw`Index \(n\)`,1,60,5);
  draw=()=>{const n=+$('#n').value,path=f=>Array.from({length:201},(_,i)=>`${i?'L':'M'} ${55+510*i/200} ${260-205*f(i/200)}`).join(' ');return figure(line(55,260,565,260,'#99aa8b')+line(55,55,55,260,'#99aa8b')+`<path d="${path(x=>x**n)}" fill="none" stroke="#28613b" stroke-width="3"/><path d="${path(x=>x/n)}" fill="none" stroke="#99782d" stroke-width="3"/>`,String.raw`Green: \(x^n\); brown: \(x/n\), on \([0,1]\), with \(n=${n}\). For \(f_n(x)=x^n\), the pointwise limit is \(f(x)=0\) for \(x<1\) and \(f(1)=1\); \(\sup_{[0,1]}|f_n-f|=1\), and the supremum is not attained. For \(g_n(x)=x/n\), \(\|g_n\|_\infty=1/n=${(1/n).toFixed(3)}\), so convergence to \(0\) is uniform.`);};
 }else if(kind==='taylor'){
  controls=range('degree',String.raw`Taylor degree \(m\)`,0,12,3);
  draw=()=>{const n=+$('#degree').value;let fact=1;for(let k=2;k<=n+1;k++)fact*=k;const polynomial=x=>{let s=1,t=1;for(let k=1;k<=n;k++){t*=x/k;s+=t;}return s;},path=f=>Array.from({length:201},(_,i)=>`${i?'L':'M'} ${55+510*i/200} ${270-75*f(-1+2*i/200)}`).join(' ');return figure(line(55,270,565,270,'#99aa8b')+`<path d="${path(Math.exp)}" fill="none" stroke="#28613b" stroke-width="3"/><path d="${path(polynomial)}" fill="none" stroke="#99782d" stroke-width="2"/>`,String.raw`Green: \(e^x\); brown: \(p_m(x)=\sum_{k=0}^{m}x^k/k!\), with \(m=${n}\) on \([-1,1]\). Uniform remainder bound: \(\|e^x-p_m\|_\infty\le e/(m+1)!=${(Math.E/fact).toPrecision(4)}\).`);};
 }else return;
 area.innerHTML=`<div class="visual-controls">${controls}</div><div id="visual-output"></div>`;
 const update=async()=>{const out=$('#visual-output');if(window.MathJax?.typesetClear)MathJax.typesetClear([out]);out.innerHTML=draw();await typeset();};
 $$('#visual-area input, #visual-area select').forEach(e=>e.oninput=()=>update().catch(fail));
 $('#visual-output').innerHTML=draw();
}
async function start(){
 try{const [problems,exams,library,audit]=await Promise.all(['problems','exams','library','audit'].map(async n=>{const r=await fetch(`data/${n}.json`);if(!r.ok)throw Error(`Cannot load ${n}.`);return r.json();}));data={problems,exams,...library,audit};for(const [name,list] of [['problem',problems],['exam',exams],['module',data.modules],['lesson',data.lessons]])data[name+'Map']=Object.fromEntries(list.map(x=>[x.id,x]));data.cards=makeCards();ids={problems:new Set(problems.map(p=>p.id)),cards:new Set(data.cards.map(c=>c.id)),lessons:new Set(data.lessons.map(l=>l.id))};progress=emptyProgress();try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)progress=validateProgress(JSON.parse(saved),ids);}catch{announce('Saved browser data could not be loaded. You can import a backup on the progress page.');}updateSummary();window.addEventListener('hashchange',()=>render().catch(fail));await render();}catch(e){fail(e);}
}
function fail(e){console.error(e);content.innerHTML=`<h1>Study material could not load</h1><p class="error">${esc(e.message)}</p><p>Start the local study server and open its localhost address. Opening index.html directly does not support loading the study data.</p>`;}
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();main.focus();main.scrollIntoView();});
start();
